parameters:
#    ideahq_swagger_ui.example.class: IdeaHQ\Bundle\SwaggerUIBundle\Example

services:
#    ideahq_swagger_ui.example:
#        class: %ideahq_swagger_ui.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
