ideahq_swagger_ui_static_resource_list:
    path: /
    defaults:
        _controller: IdeahqSwaggerUIBundle:StaticResources:resourceList

ideahq_swagger_ui_static_api_declaration:
    path: /{resource}
    defaults:
        _controller: IdeahqSwaggerUIBundle:StaticResources:apiDeclaration
